- name: Dokumentace ke Kubernetes s podporou Azure Arc
  href: index.yml
- name: Přehled
  items:
    - name: Informace o Kubernetes s podporou služby Arc
      href: overview.md
- name: Návody
  items:
    - name: Připojení ke službě Azure Arc
      items:
        - name: Připojení clusteru
          href: connect-cluster.md
        - name: Instanční objekt pro onboarding
          href: create-onboarding-service-principal.md
    - name: Spravovat
      items:
        - name: Nasazení konfigurací s využitím GitOps
          href: use-gitops-connected-cluster.md
        - name: Nasazení diagramů Helmu s využitím GitOps
          href: use-gitops-with-helm.md
        - name: Vynucení GitOps s využitím Azure Policy
          href: use-azure-policy.md
        - name: Monitorování s využitím Azure Monitoru pro kontejnery
          href: ../../azure-monitor/insights/container-insights-enable-arc-enabled-clusters.md?toc=/azure/azure-arc/kubernetes/toc.yml
        - name: Zásady řízení přístupu s využitím Azure Policy
          href: ../../governance/policy/concepts/policy-for-kubernetes.md?toc=/azure/azure-arc/kubernetes/toc.yml
        - name: Nasazení úloh IoT
          href: deploy-azure-iot-edge-workloads.md
    - name: Řešení potíží
      href: Troubleshooting.md
- name: Odkaz
  items:
    - name: Integrované služby Azure Policy
      displayName: 'samples, policies, definitions'
      href: policy-reference.md
- name: Zdroje a prostředky
  items:
    - name: Rychlé zprovoznění služby Azure Arc
      href: 'https://github.com/microsoft/azure_arc'